import { layout } from "./layout.js";

export function privacyPage(): string {
  return layout({
    title: "humanpass — privacy policy",
    body: `
    <nav class="nav">
      <a href="/" class="nav-brand">humanpass</a>
      <span></span>
    </nav>

    <h1>Privacy Policy</h1>
    <p style="color:#888;font-size:0.9rem;">Last updated: February 2025</p>

    <div class="section">
      <h2>What humanpass does</h2>
      <p>humanpass lets you prove you're a real person using your device's biometrics (Face ID, fingerprint). You get a verification link that anyone can check.</p>
    </div>

    <div class="section">
      <h2>What we store</h2>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li>A random user ID (not linked to your identity)</li>
        <li>Your passkey's public key and credential ID (generated by your device)</li>
        <li>Your verification link short codes</li>
        <li>A session cookie to keep you logged in</li>
      </ul>
      <p>That's it. No name, no email, no phone number, no tracking.</p>
    </div>

    <div class="section">
      <h2>What we do NOT store or access</h2>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li><strong>Your biometrics</strong> &mdash; Face ID, fingerprints, etc. never leave your device. We only receive a cryptographic signature that proves the check passed.</li>
        <li><strong>Personal information</strong> &mdash; We don't ask for or store any personally identifiable information.</li>
        <li><strong>Tracking data</strong> &mdash; No analytics, no third-party scripts, no advertising.</li>
      </ul>
    </div>

    <div class="section">
      <h2>Cookies</h2>
      <p>We use a single session cookie to keep you logged in. It's strictly functional &mdash; no tracking, no analytics. It expires when your session ends.</p>
    </div>

    <div class="section">
      <h2>Where your data lives</h2>
      <p>Data is stored on Cloudflare's infrastructure (D1 database and KV store) in the EU (Western Europe region). Cloudflare acts as our data processor.</p>
    </div>

    <div class="section">
      <h2>Your rights (GDPR)</h2>
      <p>Since we don't collect personal information, there's very little data to exercise rights over. However, if you want your account and associated data deleted, contact us and we'll remove it.</p>
    </div>

    <div class="section">
      <h2>Contact</h2>
      <p>Questions about this policy? Reach us at <a href="mailto:privacy@humanpass.dev">privacy@humanpass.dev</a>.</p>
    </div>

    <footer style="text-align:center;padding:2rem 0 1rem;color:#aaa;font-size:0.8rem;">
      <a href="/" style="color:#aaa;">humanpass</a>
    </footer>
    `,
  });
}
