import { layout } from "./layout.js";

export function privacyPage(): string {
  return layout({
    title: "humanpass — privacy policy",
    body: `
    <nav class="nav">
      <a href="/" class="nav-brand">humanpass</a>
      <span></span>
    </nav>

    <h1>Privacy Policy</h1>
    <p style="color:#888;font-size:0.9rem;">Last updated: February 2026</p>

    <div class="section">
      <h2>Data controller</h2>
      <p>humanpass is operated by Jordi, an individual based in the EU. For any questions about this policy or your data, contact <a href="mailto:info@human-pass.org">info@human-pass.org</a>.</p>
    </div>

    <div class="section">
      <h2>What humanpass does</h2>
      <p>humanpass lets you prove you're a real person using your device's biometrics (Face ID, fingerprint). You get a short-lived verification link that anyone can check. We also offer a Chrome browser extension that provides the same functionality.</p>
    </div>

    <div class="section">
      <h2>Legal basis for processing (GDPR Art. 6)</h2>
      <p>We process your data based on <strong>legitimate interest</strong>: providing the verification service you chose to use. We only process the minimum data necessary for the service to function.</p>
    </div>

    <div class="section">
      <h2>What we store</h2>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li>A random user ID (not linked to your real identity)</li>
        <li>Your passkey's public key, credential ID, and authenticator metadata (generated by your device)</li>
        <li>Your verification link short codes and creation timestamps</li>
        <li>A session cookie to keep you logged in</li>
      </ul>
      <p>We do not collect your name, email, phone number, or any other directly identifying information.</p>
    </div>

    <div class="section">
      <h2>What we do NOT store or access</h2>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li><strong>Your biometrics</strong> &mdash; Face ID, fingerprints, etc. never leave your device. We only receive a cryptographic signature that proves the check passed.</li>
        <li><strong>Tracking data</strong> &mdash; No analytics, no third-party scripts, no advertising.</li>
      </ul>
    </div>

    <div class="section">
      <h2>Temporary data</h2>
      <p>During the verification flow, we temporarily store:</p>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li><strong>Session tokens</strong> &mdash; expire after 60 seconds.</li>
        <li><strong>QR sync tokens</strong> &mdash; used to connect your phone to your desktop; expire after 5 minutes.</li>
        <li><strong>Referrer origins</strong> &mdash; the origin of the site where a verification link is clicked, stored temporarily to detect fraud; expire after 5 minutes.</li>
      </ul>
    </div>

    <div class="section">
      <h2>Data retention</h2>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li><strong>Verification links</strong> &mdash; expire after 60 seconds.</li>
        <li><strong>Sessions</strong> &mdash; expire after 60 seconds.</li>
        <li><strong>User accounts and passkey credentials</strong> &mdash; stored until you request deletion.</li>
        <li><strong>Temporary data</strong> (challenges, sync tokens, referrer checks) &mdash; automatically deleted within 5 minutes.</li>
      </ul>
    </div>

    <div class="section">
      <h2>Cookies</h2>
      <p>We use a single session cookie (<code>session</code>) to authenticate you. It is strictly functional &mdash; no tracking, no analytics. It expires when your session ends (60 seconds).</p>
    </div>

    <div class="section">
      <h2>Chrome extension</h2>
      <p>The humanpass Chrome extension communicates only with <code>human-pass.org</code> to poll for QR sync status and display your verification link. It does not access your browsing data, read page content, or communicate with any other server.</p>
    </div>

    <div class="section">
      <h2>Where your data lives</h2>
      <p>Data is stored on Cloudflare's infrastructure (D1 database and Workers KV). Cloudflare acts as our data processor under their <a href="https://www.cloudflare.com/cloudflare-customer-dpa/" style="color:#555;">Data Processing Addendum</a>.</p>
    </div>

    <div class="section">
      <h2>Third parties</h2>
      <p>We do not sell, share, or transfer your data to any third party. The only sub-processor is Cloudflare, which hosts the infrastructure.</p>
    </div>

    <div class="section">
      <h2>Your rights (GDPR)</h2>
      <p>You have the right to:</p>
      <ul style="margin:0.5rem 0 1rem 1.25rem;color:#444;">
        <li><strong>Access</strong> &mdash; request a copy of the data we hold about you.</li>
        <li><strong>Deletion</strong> &mdash; request that we delete your account and all associated data.</li>
        <li><strong>Rectification</strong> &mdash; request correction of inaccurate data.</li>
        <li><strong>Portability</strong> &mdash; request your data in a machine-readable format.</li>
        <li><strong>Object</strong> &mdash; object to our processing of your data.</li>
        <li><strong>Complaint</strong> &mdash; lodge a complaint with your local data protection authority.</li>
      </ul>
      <p>To exercise any of these rights, email <a href="mailto:info@human-pass.org">info@human-pass.org</a>.</p>
    </div>

    <div class="section">
      <h2>Changes to this policy</h2>
      <p>We may update this policy from time to time. Changes will be posted on this page with an updated date.</p>
    </div>

    <footer style="text-align:center;padding:2rem 0 1rem;color:#aaa;font-size:0.8rem;">
      <a href="/" style="color:#aaa;">humanpass</a>
    </footer>
    `,
  });
}
